### ISSUE TITLE
KBMAG crashes when compiled with clang and optimisations

### ISSUE THREAD

**Issue by markuspf** [gap-packages/kbmag#7] opened 2017-02-01 15:27 UTC
The following code ends in kbmag code segfaulting

```
gap> F:=FreeGroup("a","b","c");;
gap> a:=F.1;;b:=F.2;;c:=F.3;;
gap> G:=F/[Comm(a,Comm(a,b))*c^-1, Comm(b,Comm(b,c))*a^-1,
> Comm(c,Comm(c,a))*b^-1];;
gap> R:=KBMAGRewritingSystem(G);
rec(
           isRWS := true,
          silent := true,
  generatorOrder := [_g1,_g2,_g3,_g4,_g5,_g6],
        inverses := [_g2,_g1,_g4,_g3,_g6,_g5],
        ordering := "shortlex",
       equations := [
         [_g2*_g4*_g2*_g3*_g1,_g5*_g4*_g2*_g3],
         [_g4*_g6*_g4*_g5*_g3,_g1*_g6*_g4*_g5],
         [_g6*_g2*_g6*_g1*_g5,_g3*_g2*_g6*_g1]
       ]
)

gap> SetInfoLevel(InfoRWS,2);
gap> AutomaticStructure(R,true);
```

when compiled (on a Mac) with clang.

**Comment by fingolfin** [comment] 2017-02-01 15:30
I can reproduce this on OS X 10.11.6 (15G1217) with clang-800.0.42.1 (Apple LLVM version 8.0.0). It dies like this:
```
	#There are 271 word-differences.
  #eqn_factor=203, states_factor=200 - halting.
	#There are 271 word-differences.
  #eqn_factor=203, states_factor=200 - halting.
#Halting with 63832 equations.
#First word-difference machine with 271 states computed.
#Second word-difference machine with 271 states computed.
  #eqn_factor=203, states_factor=200
#System is confluent, or halting factor condition holds.
  #Exit status is 0

#Running program to construct word-acceptor and multiplier automata
  /Users/mhorn/Projekte/GAP/repos/pkg/kbmag/bin/x86_64-apple-darwin15.6.0-gcc-default64/gpmakefsa -l -v /tmp/gaptempfile.vPryR5
/Users/mhorn/Projekte/GAP/repos/pkg/kbmag/bin/x86_64-apple-darwin15.6.0-gcc-default64/autgroup: line 133: 25160 Segmentation fault: 11  $GPMAKEFSA $gpmakefsaflags $groupname
#Program to construct word-acceptor and multiplier automata failed. Giving up.
#I  Computation was not successful.
```

**Comment by markuspf** [comment] 2017-02-01 15:43
I can also reproduce this with clang 3.7 on DragonFlyBSD. using

```
gmake CC="clang37" COPT=""
```

makes the problem go away.

**Comment by markuspf** [comment] 2017-02-01 15:45
(Note: I understand that this is by no means a fix, just a bandaid)

**Comment by fingolfin** [comment] 2017-12-05 22:25
Unfortunately it seems that I get this crash also with GCC 7 on my Mac, and with all optimizations turned off.

On the upside, I verified that this also happens with the old KBMAG 1.5 and GAP 4.7, so it's not a regression we introduced when cleaning up the code.

**Comment by fingolfin** [comment] 2017-12-05 22:30
It also crashes with clang-3.7 and empty `COPT` for me. Hm, so much for that workaround.

**Comment by fingolfin** [comment] 2017-12-05 22:51
OK, turns out my crashes are not caused by a compiler bug, but are indeed a regression (introduced by me :-/) and which is fixed in f7282c26a0c46d2d984e37da097ee681dc8d71a1

**Comment by fingolfin** [comment] 2017-12-05 23:01
(I should add that the regression was introduced after the last release *phew*)

**Comment by fingolfin** [comment] 2017-12-06 08:43
I believe f7282c26a0c46d2d984e37da097ee681dc8d71a1 fixes this, by virtue of removing the undefined behaviour which might lead to a compiler optimizing the code such that it'd crash in the way shown here.

At least I cannot reproduce the problem anymore, even with clang-3.7 and -O2 or -O3

**Closed by fingolfin** 2017-12-06 08:43 UTC
