### ISSUE TITLE
AutomaticStructure not working correctly? 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/kbmag#9] opened 2017-12-05 17:35 UTC
Attempting manual Example 5 (p.15) on my system gives the following error.  Is it just me? 
```
gap> R;
rec(
           isRWS := true,
  generatorOrder := [_g1,_g2,_g3,_g4,_g5,_g6],
        inverses := [_g2,_g1,_g4,_g3,_g6,_g5],
        ordering := "shortlex",
       equations := [
         [_g2*_g4*_g2*_g3*_g1,_g5*_g4*_g2*_g3],
         [_g4*_g6*_g4*_g5*_g3,_g1*_g6*_g4*_g5],
         [_g6*_g2*_g6*_g1*_g5,_g3*_g2*_g6*_g1]
       ]
)

gap> AutomaticStructure( R, true );
#I  Calling external automatic groups program.
#Running Knuth-Bendix Program
  /Applications/gap/my-dev/pkg/kbmag/bin/x86_64-apple-darwin16.7.0-gcc-default64/kbprog -mt 20 -hf 100 -cn 0 -wd -me 262144 -t 500 /tmp/gaptempfile.2LzNjE
#Halting with 63832 equations.
#First word-difference machine with 271 states computed.
#Second word-difference machine with 271 states computed.
#System is confluent, or halting factor condition holds.

#Running program to construct word-acceptor and multiplier automata
  /Applications/gap/my-dev/pkg/kbmag/bin/x86_64-apple-darwin16.7.0-gcc-default64/gpmakefsa -l /tmp/gaptempfile.2LzNjE
/Applications/gap/my-dev/pkg/kbmag/bin/x86_64-apple-darwin16.7.0-gcc-default64/autgroup: line 133:  2574 Segmentation fault: 11  $GPMAKEFSA $gpmakefsaflags $groupname
#Program to construct word-acceptor and multiplier automata failed. Giving up.
#I  Computation was not successful.
false
```

**Comment by fingolfin** [comment] 2017-12-05 22:25
This is a duplicate of issue #7, so no, this is not just you. 

The problem seems to be that `kbmag` is very old C (predating ANSI C), and relies on undefined behavior (indeed, the old kbmag 1.5 does not even compile anymore with recent C compilers).

Closing this in favor of that other issue.

**Closed** 2017-12-06 16:26 UTC
